spring.application.name=project
spring.server.port=8080
# spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/SmartLedgerDB?authSource=admin

# spring.elasticsearch.uris=http://localhost:9200


spring.data.mongodb.uri=mongodb://admin:admin@mongo:27017/smartledger?authSource=admin
spring.elasticsearch.uris=http://elasticsearch:9200